import Head from "next/head";

const SEO = ({ pageTitle }) => (
  <>
    <Head>
      <title>{process.env.NEXT_PUBLIC_REACT_APP_NAME}</title>
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="description" content="Generated by create next app" />
      <meta name="robots" content="noindex, follow" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <link rel="icon" href="/kingsLogo.png" />
    </Head>
  </>
);
 
export default SEO;
